stages:
  - deploy

variables:
  PLUGIN_NAME: RedbullTv
  ICON_FILE: RedBullTvIcon.png
  SCRIPT_FILE: RedBullTvScript.js
  CONFIG_FILE: RedBullTvConfig.json

deploy-master:
  stage: deploy
  variables:
    PRE_RELEASE: "false"
  script:
    - sh deploy.sh
  only:
    - master

deploy-dev:
  stage: deploy
  variables:
    PRE_RELEASE: "true"
  script:
    - sh deploy.sh
  only:
    - dev
